name: applebanon
description: "A new Flutter project."
publish_to: 'none' # Keeps the package private

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0" # Ensures compatibility with Dart 3.5.x

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
